### ISSUE TITLE
🐛 Bug: unnecessary files published

### ISSUE THREAD

**Issue by bradzacher** [JoshuaKGoldberg/console-fail-test#200]
### Bug Report Checklist

- [X] I have tried restarting my IDE and the issue persists.
- [X] I have pulled the latest `main` branch of the repository.
- [X] I have [searched for related issues](https://github.com/JoshuaKGoldberg/console-fail-test/issues?q=is%3Aissue+label%3A%22type%3A+bug%22) and found none that matched my issue.

### Expected

The npm package contains the minimal files required to run the code

### Actual

https://unpkg.com/browse/console-fail-test@0.1.8/

![image](https://user-images.githubusercontent.com/7462525/231607754-879e93f5-7b15-447d-ad76-48bb6c6f82df.png)

### Additional Info

Can either use `.npmignore` to ignore files, or `package.json` `files: string[]` to specify which files to publish.

**Comment by JoshuaKGoldberg** [comment]
AH yes thanks - at some point Soon ™️ I will go through [all my repos](https://github.com/JoshuaKGoldberg#what-im-working-on) and standardize their tooling on [template-typescript-node-package](https://github.com/JoshuaKGoldberg/template-typescript-node-package). [Which does use `package.json` `files: string[]`](https://github.com/JoshuaKGoldberg/template-typescript-node-package/blob/3fcb71530ebd40821d1c647c80036e0365afc714/package.json#L13).

(I've been procrastinating doing that as there are still some niceties (https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/23, https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/139, https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/303, https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/312, https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/319, https://github.com/JoshuaKGoldberg/template-typescript-node-package/issues/371) I'd like to get in first, so I don't have to re-apply them to all the repos)

This particular issue should be pretty straightforward to port to console-fail-test / other repos if you'd like to have it fixed in the meantime! Accepting PRs. Thanks for filing!
