### ISSUE TITLE
Allow being used inside Jest beforeAll

### ISSUE THREAD

**Issue by kopax-polyconseil** [JoshuaKGoldberg/console-fail-test#72]
Hello, we are trying to ugprade jest to latest and encounter issue in our upgrade branch with `consol-fail-test`: https://github.com/pass-culture/pass-culture-app-native/pull/3271

example: 
```
  ● Test suite failed to run

    Cannot add a hook after tests have started running. Hooks must be defined synchronously.

      30 |
      31 | global.beforeAll((done) => {
    > 32 |   consoleFailTestModule.cft({
         |                         ^
      33 |     testFramework: 'jest',
      34 |     spyLibrary: 'jest',
      35 |     console: allowConsoleRuntimeConfig,

      at eventHandler (node_modules/jest-circus/build/eventHandler.js:113:11)
      at Object.after (node_modules/console-fail-test/src/environments/jest.js:10:13)
      at Object.<anonymous>.exports.cft (node_modules/console-fail-test/src/cft.js:20:21)
      at Object.cft (src/tests/setupTests.js:32:25)

```
It seems it does not support the latest jest version, is there a workaroud to keep using console-fail-test or a way we can help?

**Comment by kopax-polyconseil** [comment]
solve by moving `consoleFailTestModule.cft({` outside the beforeAll.

**Comment by JoshuaKGoldberg** [comment]
Hey thanks for posting this - cft should emit a better error in this case. Marking as accepting PRa.

**Comment by kopax-polyconseil** [comment]
Actually, it didn't fix it as the test are still failing. We opened a branch here https://github.com/pass-culture/pass-culture-app-native/tree/update-jest-27 but can't perform the upgrade to jest 27 because if this :(

If you have a clue on how to solve this ?

**Comment by kopax-polyconseil** [comment]
Hello @JoshuaKGoldberg , this is blocking the jest 26 to 27 upgrade, do you have any indication that could help us move forward? 
Thanks in advance!

**Comment by JoshuaKGoldberg** [comment]
I took a deeper look at how this gets run in https://github.com/pass-culture/pass-culture-app-native/pull/3306, as mentioned in https://github.com/JoshuaKGoldberg/console-fail-test/issues/64#issuecomment-1195566588. If you're interested you should be able to modify [`environments/jest.ts`](https://github.com/Codecademy/console-fail-test/blob/6343c24f11d89cb0a7394e6efcfac03d9ae0993b/src/environments/jest.ts#L19) -- see [`Development.md`](docs/Development.md) for some architecture docs.

Right now, the Jest environment code calls to the global Jest `afterEach` function inside its `after` hook:

```ts
return {
  after(callback: (afterHooks: TestAfterHooks) => void) {
    afterEach(() => {
      callback({
        reportComplaint({ error }) {
          throw error;
        },
      });
    });
  },
  // ...
};
```

That `after` hook is what gets called inside [`consoleFailTestModule.cft({ ... })`](https://github.com/Codecademy/console-fail-test/blob/6343c24f11d89cb0a7394e6efcfac03d9ae0993b/src/cft.ts#L15). So, if Jest is no longer allowing `afterEach` to be called where you're calling it, the environment will have to call `afterEach` earlier.

I'm betting you could modify the code to something like:

```ts

const afterEachCallback = [() => {}];

afterEach(() => {
  afterEachCallback[0]();
});

return {
  after(callback: (afterHooks: TestAfterHooks) => void) {
    afterEachCallback[0] = () => callback({
      reportComplaint({ error }) {
        throw error;
      }
    });
  },
  // ...
};
```

That's just a sketch. I don't have the time to do this myself as your usage pattern isn't one I've come across or needed to use in any of my projects. But this issue is marked as `accepting prs` if you'd like to contribute it yourself or [sponsor me](https://github.com/sponsors/JoshuaKGoldberg) to do it for you. Cheers!

**Comment by kopax-polyconseil** [comment]
Thank you for the detailed explanation. I will take a look tomorrow and let you know for the PR fix. I appreciate that you still try to help during your vacation. One thing, I didn't got why you initialized an array for just a callback function, I'll try without first.

**Comment by kopax-polyconseil** [comment]
I just opened a PR as it seems to work well : https://github.com/JoshuaKGoldberg/console-fail-test/pull/76
